name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-api.txt

      - name: Run pytest
        env:
          # Make src/ importable (same as setting PYTHONPATH=$PWD)
          PYTHONPATH: ${{ github.workspace }}

          # Tell the API tests to load your saved model file
          USE_MLFLOW: "0"
          MODEL_PATH: ${{ github.workspace }}/notebooks/models/rf_iris.pkl
        run: |
          pytest -q
